### PR TITLE
Create setup.py

### PR DESCRIPTION
**Pull request by amo13**
Needed for packaging the library on Archlinux.

### CODE REVIEW

**Comment by amo13** [comment]
Do not merge just yet, I need to test, check and fix things...

**Comment by stumpylog** [comment]
Interesting, arch can't produce a wheel (or it's equivalent) from the pyproject file?  I kind of assumed that would be enough

**Comment by amo13** [comment]
I don't know, never actually worked with python. I'll check that.

**Comment by stumpylog** [comment]
It'd be nice if that possible, just glancing at it as is, it seems like duplicate information. But it it ends up being necessary...

**Comment by amo13** [comment]
Alright, just ignore my PR: I should have read [the wiki](https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517)) again. `setup.py` seems to be deprecated and packaging appears to work just fine using the new installation method. 
Thanks for your messages though!

**Comment by stumpylog** [comment]
Great, glad to hear it and thanks for the packaging.  Didn't really expect anyone would really even find this

**Pull request closed without merging**
